name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: check out repository
      uses: actions/checkout@v2

    - name: install tree
      run: sudo apt install -y tree

    - name: build
      working-directory: ./linux/touchpad
      run: ./build.sh

    - run: tree .

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kankaku-linux-touchpad-ubuntu-20.04
        path: ./linux/touchpad/kankaku
