name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-20.04

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build
      run: ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kankaku-ubuntu-20.04
        path: kankaku
